spring:
  application:
    name: Aservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/Microservice-a?serverTimezone=UTC
    username: root
    password: mima8ge8


  thymeleaf:
    cache: false

server:
  port: 18080

