#spring:
#  application:
#    name: xxxxx
#
#  zipkin:
#    base-url: http://10.10.56.10:9411/ #zipkin 服务器地址
#    discoveryClientEnabled: false   #关闭服务发现,否则springcloud 会把zipkin 的url当做服务名称
#    sender:
#      type: web #设置使用http 的方式传输数据
#
#  sleuth:
#    sampler:
#      probability: 1 #抽样采集率,默认0.1==10%
